# Generated by Django 5.0.6 on 2026-07-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional event image shown on event cards.",
                null=True,
                upload_to="events/",
            ),
        ),
    ]
