# Generated by Django 5.0.6 on 2026-07-10 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_las_vegas_pricing_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in the event region's currency.",
                        max_digits=10,
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True,
                        help_text="One inclusion per line — shown as a checklist.",
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        help_text="Optional ribbon label, e.g. 'Most complete'.",
                        max_length=40,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["sort", "amount"],
                "unique_together": {("event", "slug")},
            },
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registrations",
                to="events.eventpackage",
            ),
        ),
    ]
