# Generated by Django 5.0.6 on 2026-07-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_las_vegas_packages"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlinePayment",
            fields=[],
            options={
                "verbose_name": "Online payment",
                "verbose_name_plural": "Online Payments",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("events.eventregistration",),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="source",
            field=models.CharField(
                choices=[("form", "Enquiry form"), ("online", "Online payment")],
                db_index=True,
                default="form",
                help_text="How the booking came in — a form enquiry or a completed online payment.",
                max_length=10,
            ),
        ),
    ]
