# Generated by Django 5.0.6 on 2026-06-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("uae", "United Arab Emirates"),
                            ("us", "United States"),
                        ],
                        default="uae",
                        max_length=8,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="e.g. privacy-policy, terms, cookies", max_length=80
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "body",
                    models.TextField(
                        help_text="Use a blank line between paragraphs. Lines ending with ':' render as headings."
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=170)),
            ],
            options={
                "ordering": ["title"],
                "unique_together": {("region", "slug")},
            },
        ),
    ]
