# Generated by Django 5.0.6 on 2026-07-01 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0003_richtext_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="custom_head",
            field=models.TextField(
                blank=True,
                help_text='Optional custom code injected into this page\'s <head> — e.g. a <script type="application/ld+json"> schema block or other head HTML.',
            ),
        ),
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                ("question", models.CharField(max_length=255)),
                (
                    "answer",
                    models.TextField(
                        help_text="Plain text. Blank lines separate paragraphs."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_faqite_content_39addd_idx",
                    )
                ],
            },
        ),
    ]
