# Generated by Django 5.0.6 on 2026-07-29 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_us_faqs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(db_index=True, max_length=500)),
                (
                    "engine",
                    models.CharField(
                        default="indexnow",
                        help_text="Which search endpoint accepted the ping.",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Submitted"),
                            ("fail", "Failed"),
                            ("skipped", "Skipped (disabled)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("http_code", models.PositiveSmallIntegerField(default=0)),
                ("response", models.CharField(blank=True, max_length=200)),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="index_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Index submission",
                "verbose_name_plural": "Index submissions",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
