# Generated by Django 5.0.6 on 2026-07-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_indexsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexsubmission",
            name="response",
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
