# Generated by Django 5.0.6 on 2026-07-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_indexsubmission_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexsubmission",
            name="source",
            field=models.CharField(
                choices=[("admin", "Admin page"), ("cli", "Command line / cron")],
                db_index=True,
                default="admin",
                help_text="Where the submission was triggered from.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="indexsubmission",
            name="engine",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("indexnow", "IndexNow (Bing/Yandex/…)"),
                ],
                default="indexnow",
                help_text="Which search endpoint the URL was sent to.",
                max_length=32,
            ),
        ),
    ]
