# Generated by Django 5.0.6 on 2026-06-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("uae", "United Arab Emirates"),
                            ("us", "United States"),
                        ],
                        default="uae",
                        max_length=8,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180)),
                (
                    "title",
                    models.CharField(
                        help_text="Role / specialty, e.g. 'Regenerative Medicine Specialist'.",
                        max_length=160,
                    ),
                ),
                (
                    "credentials",
                    models.CharField(
                        blank=True, help_text="e.g. 'MD, PhD, FRCS'.", max_length=160
                    ),
                ),
                (
                    "photo",
                    models.CharField(
                        blank=True,
                        help_text="Optional image URL/path. Leave blank to show initials avatar.",
                        max_length=300,
                    ),
                ),
                (
                    "short_bio",
                    models.CharField(
                        help_text="One/two-line summary for the team grid.",
                        max_length=255,
                    ),
                ),
                (
                    "full_bio",
                    models.TextField(
                        help_text="Full biography. Blank line separates paragraphs."
                    ),
                ),
                (
                    "specialties",
                    models.TextField(blank=True, help_text="One specialty per line."),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=170)),
            ],
            options={
                "ordering": ["order", "name"],
                "unique_together": {("region", "slug")},
            },
        ),
    ]
