# Generated by Django 5.0.6 on 2026-06-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="available_today",
            field=models.BooleanField(
                default=False, help_text="Show an 'Available Today' badge."
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="experience",
            field=models.CharField(
                blank=True, help_text="e.g. '15+ years'.", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="languages",
            field=models.CharField(
                blank=True, help_text="e.g. 'English, Arabic'.", max_length=120
            ),
        ),
    ]
