# Generated by Django 5.0.6 on 2026-06-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional card image. If set, it is shown on the home 'Our Services' slider instead of the icon.",
                null=True,
                upload_to="services/",
            ),
        ),
    ]
