# Generated by Django 5.0.6 on 2026-07-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_servicecategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Card image shown on the category page. Recommended 16:10 ratio.",
                null=True,
                upload_to="services/",
            ),
        ),
    ]
