# Generated by Django 5.0.6 on 2026-07-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="custom_head",
            field=models.TextField(
                blank=True,
                help_text='Optional custom code injected into this page\'s <head> — e.g. a <script type="application/ld+json"> schema block or other head HTML.',
            ),
        ),
    ]
