# Generated by Django 5.0.6 on 2026-07-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_alter_service_custom_head"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="custom_head",
            field=models.TextField(
                blank=True,
                help_text="Optional custom code injected into this page's &lt;head&gt; — e.g. a &lt;script type=&quot;application/ld+json&quot;&gt; schema block or other head HTML.",
            ),
        ),
    ]
