# Generated by Django 5.0.6 on 2026-07-01 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_servicecategory_custom_head"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Text / rich content"),
                            ("treatments", "Our treatments (cards from this category)"),
                            ("counters", "Counters / statistics"),
                            ("why", "Why choose us"),
                            ("faq", "FAQ (uses this service's FAQs)"),
                            ("reviews", "Patient reviews slider"),
                            ("brands", "Accreditations / brand logos"),
                            ("cta", "Call-to-action band"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True,
                        help_text="Small label above the heading.",
                        max_length=80,
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=200)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Intro / paragraph text. Blank line = new paragraph.",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="sections/"),
                ),
                (
                    "items",
                    models.TextField(
                        blank=True,
                        help_text="One item per line. • Counters: 'value | suffix | label' (e.g. 500 | + | Patients Treated). • Why choose us: 'title | description'. Not needed for other types.",
                    ),
                ),
                ("button_text", models.CharField(blank=True, max_length=60)),
                ("button_url", models.CharField(blank=True, max_length=300)),
                (
                    "background",
                    models.CharField(
                        choices=[
                            ("light", "White"),
                            ("soft", "Soft grey"),
                            ("dark", "Dark green"),
                        ],
                        default="light",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page section",
                "ordering": ["order", "id"],
            },
        ),
    ]
