# Generated by Django 5.0.6 on 2026-07-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_seed_content_blocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagesection",
            name="items",
            field=models.TextField(
                blank=True,
                help_text="One item per line. • Key benefits: just the benefit text. • Counters: 'value | suffix | label' (e.g. 500 | + | Patients Treated). • Why choose us: 'title | description'. Not needed for other types.",
            ),
        ),
        migrations.AlterField(
            model_name="pagesection",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text", "Rich text / content"),
                    ("benefits", "Key benefits (checklist)"),
                    ("treatments", "Our treatments (cards from this category)"),
                    ("counters", "Counters / statistics"),
                    ("why", "Why choose us"),
                    ("faq", "FAQ (uses this service's FAQs)"),
                    ("reviews", "Patient reviews slider"),
                    ("brands", "Accreditations / brand logos"),
                    ("cta", "Call-to-action band"),
                    ("booking", "Booking / consultation form"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
