# Generated by Django 5.0.6 on 2026-07-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0010_alter_pagesection_items_alter_pagesection_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="seo_description",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name="service",
            name="seo_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
