# Generated by Django 5.0.6 on 2026-07-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0015_longevity_ivs_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="hero_heading",
            field=models.CharField(
                blank=True,
                help_text="Keyword-rich H1 for the page hero, e.g. 'Stem Cell Therapy in Dubai'. Falls back to the service name if left blank.",
                max_length=200,
            ),
        ),
    ]
