# Generated by Django 5.0.6 on 2026-07-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0017_service_hero_headings"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="hero_heading",
            field=models.CharField(
                blank=True,
                help_text="Keyword-rich H1 for the page hero, e.g. 'Regenerative Wellness in Dubai'. Falls back to the category name if left blank.",
                max_length=200,
            ),
        ),
    ]
