# Generated by Django 5.0.6 on 2026-07-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0038_nad_iv_therapy_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Nest this service under another service to create a third-level sub-page (e.g. NAD+ IV Therapy under Longevity IVs). Leave blank for a normal top-level service.",
                limit_choices_to={"parent__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="services.service",
            ),
        ),
    ]
