# Generated by Django 5.0.6 on 2026-07-13 12:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("team", "0003_seed_real_doctors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("uae", "United Arab Emirates"),
                            ("us", "United States"),
                        ],
                        default="us",
                        max_length=8,
                    ),
                ),
                ("start", models.DateTimeField(db_index=True)),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No-show"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("online", "Online (portal)"),
                            ("phone", "Phone"),
                            ("walk_in", "Walk-in"),
                        ],
                        default="walk_in",
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for visit / service.",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="team.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-start"],
            },
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("uae", "United Arab Emirates"),
                            ("us", "United States"),
                        ],
                        default="us",
                        max_length=8,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "complaint",
                    models.TextField(
                        blank=True, help_text="Presenting complaint / symptoms."
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, help_text="Examination findings."),
                ),
                ("diagnosis", models.TextField(blank=True)),
                ("advice", models.TextField(blank=True, help_text="Advice / plan.")),
                (
                    "blood_pressure",
                    models.CharField(
                        blank=True, help_text="e.g. 120/80", max_length=20
                    ),
                ),
                ("pulse", models.CharField(blank=True, help_text="bpm", max_length=20)),
                (
                    "temperature",
                    models.CharField(blank=True, help_text="°C / °F", max_length=20),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounter",
                        to="clinic.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encounters",
                        to="team.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("uae", "United Arab Emirates"),
                            ("us", "United States"),
                        ],
                        default="us",
                        max_length=8,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, db_index=True, max_length=24, unique=True
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "tax_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("stripe_session_id", models.CharField(blank=True, max_length=200)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="clinic.appointment",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="clinic.encounter",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("sort", models.PositiveIntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="clinic.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["sort", "id"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("uae", "United Arab Emirates"),
                            ("us", "United States"),
                        ],
                        default="us",
                        max_length=8,
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(blank=True, max_length=80)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=4,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=40),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True, help_text="Known allergies, one per line."
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(
                        blank=True, help_text="Chronic conditions, past history."
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal staff notes."),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional — link a login account so the patient can use the portal.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="clinic.patient",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encounters",
                to="clinic.patient",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="clinic.patient",
            ),
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", models.CharField(max_length=160)),
                (
                    "dosage",
                    models.CharField(
                        blank=True, help_text="e.g. 500 mg", max_length=80
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True, help_text="e.g. Twice daily", max_length=80
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text="e.g. 7 days", max_length=80
                    ),
                ),
                (
                    "instructions",
                    models.CharField(
                        blank=True, help_text="e.g. After food", max_length=200
                    ),
                ),
                ("sort", models.PositiveIntegerField(default=0)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_items",
                        to="clinic.encounter",
                    ),
                ),
            ],
            options={
                "ordering": ["sort", "id"],
            },
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("doctor", "Doctor"),
                            ("reception", "Receptionist"),
                            ("admin", "Clinic Admin"),
                        ],
                        default="reception",
                        max_length=16,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("uae", "United Arab Emirates"),
                            ("us", "United States"),
                        ],
                        default="us",
                        max_length=8,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        help_text="For doctors — link to the public Doctor profile.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_profiles",
                        to="team.doctor",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["role", "user__first_name"],
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["region", "is_active"], name="clinic_pati_region_823388_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["region", "status"], name="clinic_invo_region_0b5fcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["region", "status", "start"],
                name="clinic_appo_region_9ef5f5_idx",
            ),
        ),
    ]
