# Generated by Django 5.0.6 on 2026-07-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("team", "0003_seed_real_doctors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("uae", "United Arab Emirates"),
                            ("us", "United States"),
                        ],
                        db_index=True,
                        default="us",
                        help_text="Country/region this clinic belongs to.",
                        max_length=8,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Public name, e.g. 'Brockwell Healthcare — Las Vegas'.",
                        max_length=160,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL segment, e.g. 'las-vegas'. Unique within the region.",
                        max_length=180,
                    ),
                ),
                (
                    "city",
                    models.CharField(help_text="e.g. 'Las Vegas'.", max_length=120),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Nevada'. Used to group locations.",
                        max_length=120,
                    ),
                ),
                (
                    "state_code",
                    models.CharField(blank=True, help_text="e.g. 'NV'.", max_length=8),
                ),
                (
                    "street_address",
                    models.CharField(
                        help_text="e.g. '8879 W Flamingo Rd, Ste 201'.", max_length=200
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "hours",
                    models.TextField(
                        blank=True,
                        help_text="One line per row, e.g. 'Mon–Fri: 9:00 AM – 5:00 PM'.",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "map_url",
                    models.URLField(
                        blank=True,
                        help_text="Google Maps link for the 'Get directions' button.",
                    ),
                ),
                (
                    "hero",
                    models.ImageField(
                        blank=True,
                        help_text="Hero/photo for the location page and listing card.",
                        null=True,
                        upload_to="locations/",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        blank=True,
                        help_text="One-line summary for cards & hero.",
                        max_length=255,
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        blank=True,
                        help_text="Full description for the location page (blank line = new paragraph).",
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=170)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="The main/HQ clinic for this region (shown first).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "doctors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Clinicians who practise at this location.",
                        related_name="locations",
                        to="team.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "order", "city"],
                "indexes": [
                    models.Index(
                        fields=["region", "is_active"],
                        name="locations_l_region_bdff6c_idx",
                    )
                ],
                "unique_together": {("region", "slug")},
            },
        ),
    ]
